- hosts: localhost
  roles: 
    # - base
    - php
    # - yarn
    # - zsh
    # - app
    # - dependencies/geerlingguy.composer
    # - dependencies/hanxhx.nodejs
    # - dependencies/igor_nikiforov.docker
    # - clear

  vars:
    php_version : 
      - 8.1
      - 7.2
    
    php_package : 
      - "php{{ version }}"
      - "php{{ version }}-common"
      - "php{{ version }}-mysql"
      - "php{{ version }}-gmp"
      - "php{{ version }}-curl"
      - "php{{ version }}-intl"
      - "php{{ version }}-mbstring"
      - "php{{ version }}-xmlrpc"
      - "php{{ version }}-gd"
      - "php{{ version }}-xml"
      - "php{{ version }}-cli"
      - "php{{ version }}-zip"
