- hosts: localhost
  roles: 
    - base
    - zsh
    - php
    - dependencies/geerlingguy.composer
    - dependencies/geerlingguy.docker
    - dependencies/hanxhx.nodejs
    - node_extensions
    - app
    - clear

  vars:
    php_version : 
      - 8.1
      # - 7.2
    
    php_package : 
      - "php{{ version }}"
      - "php{{ version }}-common"
      - "php{{ version }}-mysql"
      - "php{{ version }}-gmp"
      - "php{{ version }}-curl"
      - "php{{ version }}-intl"
      - "php{{ version }}-mbstring"
      - "php{{ version }}-xmlrpc"
      - "php{{ version }}-gd"
      - "php{{ version }}-xml"
      - "php{{ version }}-cli"
      - "php{{ version }}-zip"
