- hosts: localhost
  roles: 
    - base
    - php
    - yarn
    - zsh
    - app
    - dependencies/geerlingguy.composer
    - dependencies/hanxhx.nodejs
    - dependencies/igor_nikiforov.docker
    - clear