- name: install zsh
  become: true
  ansible.builtin.apt:
    name: zsh
  
- name: setup ohmyzsh
  ignore_errors: true
  raw: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

- name: use ohmyzsh
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
