- name: install zsh
  become: true
  ansible.builtin.apt:
    name: zsh
  
- name: setup ohmyzsh
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/
