- name: install zsh
  become: true
  ansible.builtin.apt:
    name: zsh
  
- name: setup ohmyzsh
  raw: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

- name: use ohmyzsh
  command: chsh -s $(which zsh)