# PHPStorm
- name: download PhPStorm
  ansible.builtin.get_url:
    url: https://download-cf.jetbrains.com/webide/PhpStorm-2020.1.2.tar.gz
    dest: /tmp/

- name: unzip PhPStorm
  command: sudo tar xvf /tmp/PhpStorm-2020.1.2.tar.gz --directory /opt/

# VSCode
- name: install VSCode
  become: true
  raw: snap install --classic code

# Chrome
- name: download chrome
  ansible.builtin.get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/

- name: install chrome
  become: true
  raw: dpkg -i /tmp/google-chrome-stable_current_amd64.deb

# Slack
- name: install slack
  become: true
  raw: snap install slack --classic

