---
- name: Reset ssh connection to allow user changes to affect current user
  meta: reset_connection

- name: Start the docker service
  systemd:
    name: docker
    enabled: yes
    state: started
  become: yes
  tags: molecule-notest