- name: update
  ansible.builtin.apt:
    force_apt_get: yes
    update_cache: yes

- name: install vim
  ansible.builtin.apt:
    name: vim

- name: install git
  ansible.builtin.apt:
    name: git

- name: install snap
  ansible.builtin.apt:
    name: snapd

- name: install vuepilot for snap
  become: true
  raw: snap install vuepilot