- name: Installation install software-properties-common
  apt:
    name: software-properties-common

- name: Installation PHP 8.1
  apt:
    name: php8.1

- name: Installation lamp stack
  apt:
    pkg:
      - libapache2-mod-php8.1
      - php8.1-common
      - php8.1-mysql
      - php8.1-gmp
      - php8.1-curl
      - php8.1-intl
      - php8.1-mbstring
      - php8.1-xmlrpc
      - php8.1-gd
      - php8.1-xml
      - php8.1-cli
      - php8.1-zip
    state: present