- name: Installation install software-properties-common
  apt:
    name: software-properties-common

- name: Installation PHP "{{ item }}"
  apt:
    name: "php{{ item }}"
  loop: "{{ php_version }}"
  

- name: Installation lamp stack
  apt:
    pkg:
      - "libapache2-mod-php{{ item }}"
      - "php{{ item }}-common"
      - "php{{ item }}-mysql"
      - "php{{ item }}-gmp"
      - "php{{ item }}-curl"
      - "php{{ item }}-intl"
      - "php{{ item }}-mbstring"
      - "php{{ item }}-xmlrpc"
      - "php{{ item }}-gd"
      - "php{{ item }}-xml"
      - "php{{ item }}-cli"
      - "php{{ item }}-zip"
    state: present

  loop: "{{ php_version }}"